### ISSUE TITLE
Bauarten und Typen aufräumen?

### ISSUE THREAD

**Issue by ottoxt** [CAFM-Connect/CAFM-Connect#124]
Im Katalog gehen die Merkmale Bauart und Typ recht durcheinander. Wir sollten uns überlegen, ob wir das vor einer Veröffentlichung aufräumen.

- **Typ** sollte im Sinne von Ifc-Typen verstanden werden:  Drehtür, Schiebetür; Personenaufzug, Lastenaufzug
- **Bauart** sollte das WIE der Ausführung konkretisieren: einflügelig, zweiflügelig; freistehend, eingebaut

Alle Merkmale wurden untersucht. Diese sind zu ändern bzw. zu klären (Diskussion berücksichtigen):

- [x] Bauart aktustische Ausgabe: 1. Schreibfehler: Ak**t**ustische Ausgabe / Hea**t**set
- [x] #133
- [x] Bauart Brandmelder: Merkmal in Typ umwandeln
- [x] Bauart Brenner: Merkmal in Typ umwandeln
- [x] #135
- [x] #134
- [x] #136
- [x] #138
- [x] #137
- [x] #144
- [x] Bauart Entsorgungsanlagen: Merkmal in Typ umwandeln
- [x] Bauart Fahrtreppe, Fahrsteig: Merkmal in Typ umwandeln
- [x] Bauart Funkbrandmelder: Merkmal in Typ umwandeln
- [x] Bauart Krananlagen: bleibt vorerst Bauart, da auch ein Feld Typ vorh. ist. Typ wurde abgekündigt.
- [x] Bauart Löschanlagen: Merkmal in Typ umwandeln
- [x] #139
- [x] #143
- [x] Bauart Sanitäreinrichtungen: wird abgekündigt
- [x] Bauart Sonst. Eingabegeräte: Merkmal in Typ umwandeln
- [x] #140
- [x] Bauart Wasserkessel: Merkmal in Typ umwandeln
- [x] Bauart Wasser-Löschanlagen: Merkmal in Typ umwandeln
- [x] #141
- [x] #142
- [x] #145

- [x] Typ Krananlagen: ortsfest/nicht ortsfest -> ggf. in "Ortsfestigkeit" umbenennen 
- [x] Typ Photovoltaikanlagen: Netzeinspeisung / Eigenverbrauch ->Merkmal "Einspeisung" und Enumwert "Mischbetrieb" 
ergänzen.

**Comment by Maqsima** [comment]
411.60 Abscheideranlagen
Typen: Abscheideranlagen für Fette, Abscheideranlagen für Leichtflüssigkeiten, Sand- und Schlammfänge, soweit diese nicht Bestandteil von Abscheideranlagen sind (Anm.: Mit Ausnahme von Stärkeabscheidern sind allen Abscheidern Schlammfänge vorzuschalten), Stärkeabscheider; Rückstausicherung und Leichtflüssigkeitssperren; Abscheideranlage aus Beton (Allgemeine bauaufsichtliche Zulassungen - DIBt)
Bauart: Fettabscheider zum Erdeinbau, Fettabscheider zur freien Aufstellung

**Comment by Maqsima** [comment]
445.10 Allgemeinbeleuchtung
Typ: natürlich, künstlich
Bauart (künstlich): Decke, Wand, Boden, mobil, Einbau (z.B. Möbel)

**Comment by Maqsima** [comment]
Typen Brandmelder: automatische, nicht automatische, in Ex-Bereichen
Bauarten (automatische): Ionisationsrauchmelder, Optische Rauchmelder, Wärmemelder, Flammenmelder, 
Durchlichtrauchmelder
Quelle: https://www.baunetzwissen.de/sicherheitstechnik/fachwissen/brandmeldeanlagen/arten-von-brand--und-rauchmelder-164928

**Comment by ottoxt** [comment]
Bei den Abscheideranlagen würden wir diese Merkmale vorschlagen:
- Bauart: Erdeinbau, freie Aufstellung
- Typen: Abscheideranlagen für Fette, Abscheideranlagen für Leichtflüssigkeiten, Sand- und Schlammfänge, Stärkeabscheider
- Material: Beton, Kunststoff, Edelstahl

**Comment by ottoxt** [comment]
Allgemeinbeleuchtung: Klasse und Merkmale sollten insgesamt überarbeitet werden.
